export { default as HomePage } from "./home-page/home-page.component";
export { default as AddNewBlog } from "./sell-car-page/add-new-blog-component";
export { default as LoginPage } from "./login-page/login-page.component";
export { default as RegistrationPage } from "./registration-page/registration-page.component";
export { default as ForgotPage } from "./forgot-page/forgot-page.component";
export { default as NewBlogsListPage } from "./new-listings-list-page/newBlogsListPage";
export { default as BlogDetailsPage } from "./blog-details-page/blogDetailsPage";
export { default as UpdateProfilePage } from "./update-profile-page/update-profile.component";
export { default as NotFoundPage } from "./not-found-page/not-found.component";
